### PR TITLE
fix #78

### LINKED ISSUE #78: Add dict cursor ability
Add the ability to get results from cursor as python dictionary (e.g {colname:value})

### PR DESCRIPTION
**Pull request by alexanderlz**
Add the ability to get dictionary resultset from cursor
filled https://opensource.dropbox.com/cla/individual/

### CODE REVIEW

**Comment by jingw** [comment]
This isn't specified by DP-API, so I'm inclined to suggest keeping this patch to yourself (perhaps as a subclass / wrapper class).

You could also use the less barren SQLAlchemy wrapper, which supports doing things like `row.column`, `row['column']`, and `row[index]`.

**Comment by alexanderlz** [comment]
Thanks for the note,
Although indeed not specified by pep-249, lot of users find it useful (see [psycopg2](http://initd.org/psycopg/docs/extras.html)/[MySQL-python](https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlcursordict.html)/[vertica-python](https://github.com/uber/vertica-python/blob/master/vertica_python/vertica/cursor.py#L248) and many others).

About the alchemy - not every task requires the usage of ORM

As pyhive user myself - I personally find it useful.

**Comment by jingw** [comment]
You can use sqlalchemy without the ORM, e.g.
```
cur = engine.execute('select * from whatever')
row = cur.fetchone()
print row.some_column
print row['some_column']
```

I'd like to punt all the fancy stuff to SQLAlchemy (less duplication and less work for me to maintain). Thanks for the contribution though!

**Comment by JimCurryWang** [comment]
So, Did Pyhive have the alternative methods just like ``pymysql.cursors.DictCursor``  ?

**Comment by JimCurryWang** [comment]
For those who have the same issue, I write a new simple ``Dict Cursor`` function(``execute``) to return a list of dict response.

```python
class Client():    
    PRESTO_ADDRESS = 'xxx'
    PRESTO_PORT = xxx
    PROTOCOL = 'https'
    USERNAME = 'xxx'
    PASSWORD = 'xxx' 
    SCHEMA = 'xxx'

    def __init__(self, batch_size=100000):
        self.conn = presto.connect( 
                        self.PRESTO_ADDRESS,
                        port = self.PRESTO_PORT, 
                        protocol= self.PROTOCOL,
                        username = self.USERNAME, 
                        password = self.PASSWORD,
                        schema = self.SCHEMA
                    )

        self.curs = self.conn.cursor()
        self.batch_size = batch_size

    def execute(self, query, types="fetchall"):
        ''' A DictCursor executor
        '''
        resp = list()

        self.curs.execute(query)
        
        colnames = [ desc[0] for desc in self.curs.description ]
        
        if types == "fetchall":
            rows = self.curs.fetchall()
        elif types == "fetchone":
            rows = self.curs.fetchone()
        else:
            raise AttributeError

        if rows:
            for tup in rows:
                resp.append( dict( zip(colnames, tup)) )

        self.curs.close()
        self.conn.close()

        return resp 
```

**Pull request closed without merging**
