### PR TITLE
Add support for pure-sasl for windows

### PR DESCRIPTION
**Pull request by devinstevenson**
@jingw Implementation copied from impyla package. Wasn't sure how best to reference that...but both packages use Apache license. 

Attempted testing pure-sasl. Any feedback appreciated. Thanks.

### CODE REVIEW

**Comment by jingw** [comment]
Sorry, haven't forgotten about this. Will take a look next week.

**Comment by devinstevenson** [comment]
Thanks @jingw! Would it be possible to cut a new version after this is merged?

**Comment by jingw** [comment]
After #132 and #135, I think I'm leaning towards having the library expose a `transport=...` option, so I don't have a combinatorial explosion of code to maintain, and you don't get blocked on PR reviews. Thoughts?

**Comment by jingw** [comment]
I'm going to push a change to make the transport customizable.

**Pull request closed without merging**
