### PR TITLE
Adding logic to use SSL thrift socket.

### PR DESCRIPTION
**Pull request by dalbrecht**

### CODE REVIEW

**Comment by mtdeguzis** [comment]
Why was this closed? I can't seem to get SSL to work. Was this not feasible?

**Comment by azeroth2b** [comment]
Hello All,
  I'm also interested in the SSL support. What happened here? Can I help
finish it? Can you give me enough direction to finish it?

~ Shawn

**Comment by darthale** [comment]
Again: why was this closed? Our Hive config supports SSL but not SASL, so we can't get pyhive to work

**Comment by pmurray** [comment]
Really need SSL support to continue using pyhive (which is otherwise great!)
I think line 87 should be this unless we want to pass a cert:
socket = thrift.transport.TSSLSocket.TSSLSocket(host, port, validate=False)

**Pull request closed without merging**
