### PR TITLE
Kangweihao/hot fix trino

### PR DESCRIPTION
**Pull request by kangweihao0321**

### CODE REVIEW

**Comment by sp-davidpichler** [comment]
Any reason this was closed and not merged?

**Comment by mkbsh** [comment]
Echoing the comment above: will this be merged at any point?

**Comment by bkyryliuk** [comment]
@kangweihao0321 I am back from vacation and can help you to get this merge if it is still needed. 

I would need a bit more detailed description & test plan and may leave a couple comments like reusing functions e.g. Trino classes could inherit from presto.

**Comment by shawnzhu** [comment]
I'd like to have this feature via either this PR or #381 as a long time pyHive user. Since there is community contribution to trino community like https://github.com/dungdm93/sqlalchemy-trino so I'd like to hear the direction of this repo on the Trino support as well.

I can see two immediate use cases out of this feature:

1. support read/write from/to Trino via pandas API
2. bridge Apache superset for Trino.

**Pull request closed without merging**
