### PR TITLE
if auth is "NONE", username and password can be provided

### PR DESCRIPTION
**Pull request by gouchaoer**
if auth is "NONE", username and password can be provided

### CODE REVIEW

**Comment by jingw** [comment]
Thanks for your interest.

- Could you explain the reason for this? i.e. what Hive settings do you need on HiveServer2 for this option to make sense? I don't see anything obvious in the Hive docs.
- Could you clean up / update the code instead of leaving it commented out? Presumably password continues to make no sense in other modes like kerberos.

**Comment by gouchaoer** [comment]
https://stackoverflow.com/questions/18186973/simple-user-password-authentication-for-hiveserver2-without-kerberos-ldap

in hiveserver2 CUSTOM mode，actually client use sasl：PLAIN（the default strategy）。
java and php client can handle this but pyhive can't.

**Comment by jingw** [comment]
Let me do some reading on CUSTOM mode and figure out the most consistent way to represent this.

**Comment by DeeeFOX** [comment]
I'm watching this issue, CUSTOM mode should be supported in the future release

**Pull request closed without merging**
